name: Release

on:
  workflow_dispatch:

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm build
      - uses: changesets/action@v2
        with:
          publish-script: pnpm release
          pr-title: Release
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NPM_CONFIG_PROVENANCE: true
